### ISSUE TITLE
Unable to use by npm installation

### ISSUE THREAD

**Issue by qew17** [MaraniMatias/img2gcode#1]
Hi, I tried to install this module, using **npm install img2gcode**, and there is just a **tsconfig.json** in **src** folder.
![_651](https://user-images.githubusercontent.com/18377799/32492065-a6f24616-c3c1-11e7-9e1f-b969ca9b0944.png)

I assume it could be caused by this line in your **.npmignore**:
`5. *.ts`

It would be great, if you could check it in the nearest time, thanks.

**Comment by MaraniMatias** [comment]
You can clone the repo or install via GitHub.

Now I do  your idea

thanks

**Comment by MaraniMatias** [comment]
You can clone the repo or install via GitHub.

Now I do your idea

thanks

**Comment by qew17** [comment]
Okay, thanks for response.
